### ISSUE TITLE
Doesn't show previous name, only current one

### ISSUE THREAD

**Issue by dimgfsatttyggfr** [isFakeAccount/psnawp#86] opened 2024-08-18 18:31 UTC
When i try to see previous psns as it's written it's possible in description, it still shows me only the current name. Sending you the code:

from psnawp_api import PSNAWP

def hex_to_decimal(hex_str):
	return str(int(hex_str, 16))
	
psnawp = PSNAWP ("")

hex_account_id = ""

decimal_account_id = hex_to_decimal(hex_account_id)

example_user_1 = psnawp.user(account_id=decimal_account_id)

print(f"Previous: {example_user_1.prev_online_id}")

Maybe there is a mistake in the code? Help

**Comment by isFakeAccount** [comment] 2024-09-02 06:31
duplicate of #85

**Closed by isFakeAccount** 2024-09-02 06:31 UTC
Labels: duplicate
